### ISSUE TITLE
Issue do Readme.md

### ISSUE THREAD

**Issue by PeterNV** [PeterNV/-GCMS-Pedro-VilaNova#1]
[README](https://github.com/PeterNV/-GCMS-Pedro-VilaNova/edit/main/README.md)
@ramidedantas
https://github.com/PeterNV/-GCMS-Pedro-VilaNova/labels/documentation

**Comment by ramidedantas** [comment]
Pedro, formate o README como está no meu repositório depois me avise aqui, para eu editar.

**Comment by PeterNV** [comment]
@ramidedantas já editei.

**Comment by ramidedantas** [comment]
Editado, pode fechar issue.
